# TODO: integrate with frontend
user_consent = True


def calculate_openai_cost(
    input_tokens: int, output_tokens: int, model: str = "gpt-4.1"
) -> float:
    """
    Calculate the estimated cost of an OpenAI API call.

    Args:
        input_tokens (int): Number of input tokens sent to the model.
        output_tokens (int): Number of output tokens generated by the model.
        model (str): The model name used for pricing. Defaults to "gpt-4.1".

    Returns:
        float: Total estimated cost in USD.
    """
    if model == "gpt-4.1":
        input_price_per_million = 2.00
        output_price_per_million = 8.00

    input_cost = (input_tokens / 1_000_000) * input_price_per_million
    output_cost = (output_tokens / 1_000_000) * output_price_per_million
    return input_cost + output_cost
